date:
  like:
    maxlike_id: 1
  media:
    max-width: 640
    max-height: 320
  data:
    url: http://localhost:8980/media
spring:
  kafka:
    consumer:
      bootstrap-servers: staging:9092
      group-id: MediaService
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "com.lovemire.date-media-service"
    producer:
      bootstrap-servers: staging:9092
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/media_service
    username: media
    password: 1234
  data:
    rest:
      basePath: /data
  application:
    name: media-service
server:
  port: ${PORT:8960}
eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone1
logging:
  level:
    org:
      springframework: info
    hibernate:
      SQL: debug
    com: debug
jwt:
  secret: SecretKey1
